/*
Eclipse XFSC TRAIN Trusted Content Resolver

XFSC TRAIN Trusted Content Resolver REST API

API version: 1.0.0
Contact: denis.sukhoroslov@telekom.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tcr

import (
	"encoding/json"
	"fmt"
)

// checks if the ValidateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValidateResponse{}

// ValidateResponse struct for ValidateResponse
type ValidateResponse struct {
	// DID verified via well-known did-configuration
	DidVerified bool `json:"didVerified"`
	// If Issuer details are found, display meta data information, public keys, schema from the trust list..?
	Endpoints []ResolvedTrustList `json:"endpoints,omitempty"`
}

type _ValidateResponse ValidateResponse

// NewValidateResponse instantiates a new ValidateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValidateResponse(didVerified bool) *ValidateResponse {
	this := ValidateResponse{}
	this.DidVerified = didVerified
	return &this
}

// NewValidateResponseWithDefaults instantiates a new ValidateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValidateResponseWithDefaults() *ValidateResponse {
	this := ValidateResponse{}
	return &this
}

// GetDidVerified returns the DidVerified field value
func (o *ValidateResponse) GetDidVerified() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.DidVerified
}

// GetDidVerifiedOk returns a tuple with the DidVerified field value
// and a boolean to check if the value has been set.
func (o *ValidateResponse) GetDidVerifiedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DidVerified, true
}

// SetDidVerified sets field value
func (o *ValidateResponse) SetDidVerified(v bool) {
	o.DidVerified = v
}

// GetEndpoints returns the Endpoints field value if set, zero value otherwise.
func (o *ValidateResponse) GetEndpoints() []ResolvedTrustList {
	if o == nil || IsNil(o.Endpoints) {
		var ret []ResolvedTrustList
		return ret
	}
	return o.Endpoints
}

// GetEndpointsOk returns a tuple with the Endpoints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidateResponse) GetEndpointsOk() ([]ResolvedTrustList, bool) {
	if o == nil || IsNil(o.Endpoints) {
		return nil, false
	}
	return o.Endpoints, true
}

// HasEndpoints returns a boolean if a field has been set.
func (o *ValidateResponse) HasEndpoints() bool {
	if o != nil && !IsNil(o.Endpoints) {
		return true
	}

	return false
}

// SetEndpoints gets a reference to the given []ResolvedTrustList and assigns it to the Endpoints field.
func (o *ValidateResponse) SetEndpoints(v []ResolvedTrustList) {
	o.Endpoints = v
}

func (o ValidateResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValidateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["didVerified"] = o.DidVerified
	if !IsNil(o.Endpoints) {
		toSerialize["endpoints"] = o.Endpoints
	}
	return toSerialize, nil
}

func (o *ValidateResponse) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"didVerified",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varValidateResponse := _ValidateResponse{}

	err = json.Unmarshal(bytes, &varValidateResponse)

	if err != nil {
		return err
	}

	*o = ValidateResponse(varValidateResponse)

	return err
}

type NullableValidateResponse struct {
	value *ValidateResponse
	isSet bool
}

func (v NullableValidateResponse) Get() *ValidateResponse {
	return v.value
}

func (v *NullableValidateResponse) Set(val *ValidateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableValidateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableValidateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValidateResponse(val *ValidateResponse) *NullableValidateResponse {
	return &NullableValidateResponse{value: val, isSet: true}
}

func (v NullableValidateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValidateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
