{{- if .Values.serviceAccount.create -}}

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "tcr-service.name" . }}-view
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: {{ include "tcr-service.name" . }}-view
subjects:
  - kind: ServiceAccount
    name: {{ include "tcr-service.serviceAccountName" . }}
{{- end }}
