apiVersion: v1
kind: Service
metadata:
  {{- if .Values.monitoring.enabled }}
  {{- with .Values.monitoring.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  name: {{ include "tcr-service.fullname" . }}
  labels:
    {{- include "tcr-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tcr-service.selectorLabels" . | nindent 4 }}
