name: Maven Build & Test

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  maven-build:
    uses: eclipse-xfsc/dev-ops/.github/workflows/docker-maven.yml@main
    with:
      java_version: '18'
      folder: clients/java
      deploy_mode: jar