name: Maven Build & Test

on:
  workflow_dispatch:
  pull_request:
  push:

permissions:
  contents: read
  actions: write

jobs:
  maven-build:
    uses: eclipse-xfsc/dev-ops/.github/workflows/maven-build.yml@main
    secrets: inherit
    with:
      java_version: '18'
