name: Maven Build & Test

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  maven-build:
    uses: eclipse-xfsc/dev-ops/.github/workflows/maven-build.yml@main
    with:
      java_version: '18'
      deploy_mode: 'jar'