name: Docker and Helm

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  dockerbuild:
    uses: eclipse-xfsc/dev-ops/.github/workflows/dockerbuild.yml@main
    secrets: inherit
    with: 
      dockerfile: service/Dockerfile
      buildContext: service
      harbor_config: "deployment/harbor.config"
      repo_name: trusted-content-resolver-service
  helm-tcr-service:
    uses: eclipse-xfsc/dev-ops/.github/workflows/helm.yml@main
    secrets: inherit
    with: 
      buildContext:  "deployment/helm/tcr-service"
      harbor_config: "deployment/harbor.config"
  client-lib:
    uses: eclipse-xfsc/dev-ops/.github/workflows/docker-maven.yml@main
    with:
      java_version: '18'
      folder: clients/java
      deploy_mode: jar
